# Generated by Django 2.1.3 on 2018-11-24 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='question',
            table='t_question',
        ),
    ]
