# Generated by Django 2.1.3 on 2018-11-25 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20181124_2353'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='choice',
            table='t_choice',
        ),
    ]
